mariadb:
  enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"

elasticsearch:
  enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

mongodb:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

postgresqlha:
  enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

mariadbgal:
  enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring