config:

  postgresqlclient:
    mapName: client-db
    name: postgresql-base-client
    volumeName: client-db
    image: jcardonar/postgresql-client
    namespace: databases

  apiPostgresql:
    replicas: 1
    name: apipostgresql
    image: jcardonar/api-postgresql
    nameApp: apipostgresql

  mariaDBClient:
    mapName: client-db
    name: mariadb-base-client
    volumeName: client-db
    image: edwardandcode/mariadb-client
    namespace: databases

  apiMariaDB:
    replicas: 1
    name: apimariadb
    image: edwardandcode/api-mariadb
    nameApp: apimariadb

  mariagaleraclient:
    mapName: m-client-db
    name: mariagalera-base-client
    volumeName: m-client-db
    image: joctan04/mariagalera-client
    namespace: databases

  apiMariagalera:
    replicas: 1
    name: apimariagalera
    image: joctan04/api-mariagalera
    nameApp: apimariagalera

  postgresqlhaclient:
    mapName: client-db
    name: postgresqlha-base-client
    volumeName: client-db
    image: vonneumannn/postgresqlha-client
    namespace: databases

  apiPostgresqlha:
    replicas: 1
    name: apipostgresqlha
    image: vonneumannn/api-postgresqlha
    nameApp: apipostgresqlha

  database:
    postgresql:
      enabled: false

    mariadb:
      enabled: true

    mariadbgalera:
      enabled: false

    postgresqlha:
      enabled: true
