config:
  
  postgresqlclient:
    mapName: client-db
    name: postgresql-base-client
    volumeName: client-db
    image: jcardonar/postgresql-client
    namespace: databases

  apiPostgresql:
    replicas: 1
    name: apipostgresql
    image: jcardonar/api-postgresql
    nameApp: apipostgresql

  mariaDBClient:
    mapName: client-db
    name: mariadb-base-client
    volumeName: client-db
    image: edwardandcode/mariadb-client
    namespace: databases

  apiMariaDB:
    replicas: 1
    name: apimariadb
    image: edwardandcode/api-mariadb
    nameApp: apimariadb

  database:
    postgresql:
      enabled: false

    mariadb:
      enabled: true