config:
  
  postgresqlclient:
    mapName: client-db
    name: postgresql-base-client
    volumeName: client-db
    image: jcardonar/postgresql-client
    namespace: databases

  apiPostgresql:
    replicas: 1
    name: apipostgresql
    image: jcardonar/api-postgresql
    nameApp: apipostgresql


  mariagaleraclient:
    mapName: client-db
    name: mariagalera-base-client
    volumeName: client-db
    image: joctan04/mariagalera-client
    namespace: databases

  apiMariagalera:
    replicas: 1
    name: apiMariagalera
    image: joctan04/api-mariagalera
    nameApp: apiMariagalera

  database:
    postgresql:
      enabled: false

    mariadb-galera:
      enabled: true