config:
  
  postgresqlclient:
    mapName: client-db
    name: postgresql-base-client
    volumeName: client-db
    image: jcardonar/postgresql-client
    namespace: databases

  apiPostgresql:
    replicas: 1
    name: apipostgresql
    image: jcardonar/api-postgresql
    nameApp: apipostgres-deployment


  database:
    postgresql:
      enabled: true